### ISSUE TITLE
Инструкция по сборке.

### ISSUE THREAD

**Issue by Zer0C00I** [hkarel/ToxPhone#1]
Пытаюсь собрать на debian 12.Пакета qt5-default нужно заменить на  qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools.
libsodium 1.0.18 собираеться но при линковке cannot find /opt/sodium/1.0.18/lib/lbsodium.a No such file or directory

**Comment by hkarel** [comment]
Здравствуйте. 
Начнем с конца. Я собираю libsodium с этого репа: https://github.com/jedisct1/libsodium.git
Собираю ветку  stable. Текущий коммит 54b04533ccaf37b417fdca69bca9662145ff9c68
Директория сборки /opt/sodium/1.0.19 
Статическая либа libsodium.a там присутствует. 
Проект ToxPhone сейчас собирается под libsodium 1.0.19 (смотрие коммит 38dbcbe0707)

**Comment by Zer0C00I** [comment]
Все разобрался libsodium компилрует библиотку в скрытую директорию .libs и их ручками надо переладывать в /opt/sodium/lib   .По поводу qt5-default начиная с debian 12 и ubuntu 21.04 пакет был убран и нужно ставить теперь все руками а именно qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04

**Comment by hkarel** [comment]
1. Изменен список необходимых deb-пакетов (1aa023e6)
2. Сейчас попросил коллегу собрать sodium на Астре. Нет там никаких скрытых папок после сборки и установки .libs
Порядок сборки:
cd libsodiun
git clean -dfx
git checkout -f
git checkout -t origin/stable
./configure --prefix=/opt/sodium/1.0.19
make 
sudo make install

Все. Файл libsodium.a на месте в директории /opt/sodium/1.0.19/lib/, никаких скрытых диреторий нет.

**Comment by Zer0C00I** [comment]
собирал так скачал тарбал с гит релизов,распаковал.зашел в директорию.Выполнил просто ./configure без префика и make.make install не делал не хотел засорять систему.Хотел я конечно тоже не прочитал что делает make install.
![image](https://github.com/hkarel/ToxPhone/assets/165159864/860accff-9f8a-4965-a199-9d254cca153e)

**Comment by hkarel** [comment]
Если указывать префикс --prefix=/opt/sodium/1.0.19 систему вы не засорите, в любой момент можно удалить директорию /opt/sodium/

**Comment by Zer0C00I** [comment]
Понятно.Считаю проблему исчерпанной.Возможно если будет время ,я напишу как собрать все с нуля и пришлю коммитом.Для тех кто еще  заинтересуется этим проектом.
